### ISSUE TITLE
Looks cool but doesn't build

### ISSUE THREAD

**Issue by rdafoe** [kjmckenzie/perimeter#1]
Several reference issues and/or missing files, interfaces, etc.

**Comment by kjmckenzie** [comment]
sorry - fixed and applied a check-in here to correct this.

Seems my last check-in included a redundant ViewvModel file BlePeripheralViewModel.cs - simply remove it from your solution and all should be good.

**Comment by kjmckenzie** [comment]
if you have other reference issues pls do share and i will investigate

**Comment by rdafoe** [comment]
No worries. Works now. Thanks!!

**Comment by rdafoe** [comment]
Will do bro
